aws/urls.py
from django.contrib import admin
from django.urls import include, path, re_path as url
from django.views.static import serve
from django.conf import settings
from . import views

app_name = 'aws'

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path ('', views.index, name='index'),
    path ('addaccount/', views.addaccount, name='addaccount'),
    path ('processaddaccount/', views.processaddaccount, name='processaddaccount'),
    path ('awsaccounts/', views.awsaccounts, name='awsaccounts'),
    path ('<int:serverid>/startreserver/', views.startreserver, name='startreserver'),
    path ('<int:serverid>/stopserver/', views.stopserver, name='stopserver'),
    path ('<str:instanceid>/instancerdp/', views.instancerdp, name='instancerdp'),
    path ('ubuntuservers/', views.ubuntuservers, name='ubuntuservers'),
    path ('<int:serverid>/startreubuntuservers/', views.startreubuntuservers, name='startreubuntuservers'),
    path ('<int:serverid>/stopubuntuservers/', views.stopubuntuservers, name='stopubuntuservers'),
    path ('windowsservers/', views.windowsservers, name='windowsservers'),
    path ('<int:serverid>/startrewindowsservers/', views.startrewindowsservers, name='startrewindowsservers'),
    path ('<int:serverid>/stopwindowsservers/', views.stopwindowsservers, name='stopwindowsservers'),    
    #ubuntuservers page

    path ('<str:area>/<str:action>/startareaservers/', views.startareaservers, name='startareaservers'),
    path ('<int:stopstart>/ssallwindowsservers/', views.ssallwindowsservers, name='ssallwindowsservers'),
    # path ('<int:serverid>/winrdpaccess/', views.winrdpaccess, name='winrdpaccess'),
]

event/urls.py
from django.contrib import admin
from django.urls import include, path, re_path as url
from django.views.static import serve
from django.conf import settings
from . import views

app_name = 'event'

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path ('', views.index, name='index'),
    path ('saveditevent/', views.saveditevent, name='saveditevent'),
    path ('delete/', views.delete, name='delete'),
    path ('edit/', views.edit, name='edit'),
    # path ('eventsetup/', views.eventsetup, name='eventsetup')
    path ('<int:eid>/eventpage/', views.eventpage, name='eventpage'),
    path ('eventpagejq/', views.eventpagejq, name='eventpagejq'),
    path ('eventpagesetup/', views.eventpagesetup, name='eventpagesetup'),

    #position
    path ('saveditpos/', views.saveditpos, name='saveditpos')
    
]

kmsystem/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path ('', views.index, name='index'),
    path ('event/', include ('event.urls')),
    path ('aws/', include ('aws.urls')),
    path ('mmaptsp2/', include ('mmaptsp2.urls')),
    path ('clients/', include ('clients.urls')),
    path ('users/', include ('users.urls')),
    path('admin/', admin.site.urls),   
    
]

event/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone
from django.utils.timezone import now

# Create your models here.
time_now = datetime.now().strftime('%H:%M')   


class Event(models.Model):
    event_name          =   models.CharField(max_length=100, verbose_name='Event Name', blank=True)
    event_type          =   models.CharField(max_length=50, verbose_name='Event Type', blank=True)
    event_date          =   models.DateField(verbose_name='Event Date',  default=now)    
    event_time          =   models.TimeField(verbose_name='Event Time',  default = time_now)
    event_setupDate     =   models.DateField(verbose_name='Event Setup Date', default=now)
    user_id             =   models.IntegerField(default=0, verbose_name='User ID', blank=True)
    user_name           =   models.CharField(max_length=50, verbose_name='User Name', blank=True)


class Event_type(models.Model):
    event_type_name     =   models.CharField(max_length=100, verbose_name='Event Type Name', blank=True)
    event_description   =   models.TextField(max_length=150, verbose_name='Event Description', blank=True)

class Event_positions(models.Model):
    eventid             =   models.IntegerField(default=0, verbose_name = "Event ID")
    position            =   models.CharField(max_length=50, verbose_name='Position', blank=True)
    avail_seats         =   models.IntegerField(default=0, verbose_name='Available Seats', blank=True)

class Candidates(models.Model):
    eventid             =   models.IntegerField(default=0, verbose_name = "Event ID")
    can_name            =   models.CharField(max_length=100, verbose_name='Name', blank=True)
    can_pos             =   models.CharField(max_length=50, verbose_name='Position', blank=True)
    can_branch          =   models.CharField(max_length=50, verbose_name= 'Branch', blank=True)
    can_CBU             =   models.FloatField(default=0, verbose_name='CBU', blank=True)
    can_savings         =   models.FloatField(default=0, verbose_name='Savings', blank=True)
    position            =   models.CharField(max_length=50, verbose_name='Position', blank=True)

class Voter(models.Model):
    eventid             =   models.IntegerField(default=0, verbose_name = "Event ID")
    voter_name          =   models.CharField(max_length=100, verbose_name='Name', blank=True)
    voter_branch        =   models.CharField(max_length=50, verbose_name='branch', blank=True)
    voter_CBU           =   models.FloatField(default=0, verbose_name='CBU', blank=True)
    voter_savings       =   models.FloatField(default=0, verbose_name='Savings', blank=True)
    # voter_regdate       =   models.DateTimeField(verbose_name='Registered Date',  default=now) 

class Key_var(models.Model):
    eventid             =   models.IntegerField(default=0, verbose_name = "Event ID")
    eventcaption        =   models.CharField(max_length=50, verbose_name='Event Caption', blank=True)


    

event/forms.py
from django import forms

from .models import Event, Event_type
from datetime import datetime

date_time_now = datetime.now()

class EventForm(forms.ModelForm):
    get_event_type  = Event_type.objects.values_list('event_type_name', flat=True)
    
    event_type = forms.ModelChoiceField(queryset=get_event_type, empty_label=None, 
                                        widget=forms.Select(attrs={'class': 'form-control', 'id': 'event_type', 'required' : True}))
                    

    class Meta:
        model       = Event
        fields      = ['event_name', 'event_type', 'event_date', 'event_time']
        widgets     = {
            'event_name' : forms.TextInput(attrs={'class': 'form-control', 'id': 'event_name', "required": True}),
            'event_date' : forms.DateInput(
                
                format=('%Y-%m-%d'), # this format for display current date to input type date
                attrs={'class': 'form-control', 
                       'placeholder': 'Select a date',
                       'type': 'date',
                    #    'value' :date_time_now,
                    #    'initial' : date_time_now.strftime('%m/%d/%Y'),
                    #    'initial' : date_time_now.strftime('%Y-%m-%d'), # this format for display current date to input type date
                       'id': 'event_date',
                       'required': True
                         # <--- IF I REMOVE THIS LINE, THE INITIAL VALUE IS DISPLAYED
                      }),
            'event_time' : forms.TimeInput(
            format=('%H:%M'),
            attrs={'class': 'form-control', 
                    'placeholder': 'Select a time',
                    'type': 'time',
                    'id': 'event_time',
                    'required': True
                        # <--- IF I REMOVE THIS LINE, THE INITIAL VALUE IS DISPLAYED
                    })
            # 'event_date' : forms.EmailInput(attrs={'class': 'form-control', 'id': 'event_date'}),
            # 'course': forms.TextInput(attrs={'class': 'form-control', 'id': 'event_setupDate'})

        }

event/views.py
from django.shortcuts import render
from .forms import EventForm
from .models import Event, Event_type, Key_var, Event_positions
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required, permission_required
from datetime import datetime, timedelta
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

@login_required(login_url= '/users/login')
def index (request):
    form                =   EventForm()
    events              =   Event.objects.values()
    eventLists          =   list(events)
    current_date        =   datetime.now()
    context             =   {'form': form, 'eventLists': eventLists, 'current_date': current_date}
    return render(request, 'event/index.html', context)

@csrf_exempt
@login_required(login_url= '/users/login')
def saveditevent (request):
    user = request.user
    if request.method   ==  'POST':
        event_form         =   EventForm(request.POST)
        
        sid                =   request.POST.get('eventpid')
        event_name         =   request.POST['event_name']
        event_type         =   request.POST['event_type']
        event_date         =   request.POST['event_date']
        event_time         =   request.POST['event_time']
        user_id            =   request.POST['user_id']
        user_name          =   request.POST['user_name']

        event_dateFormat   =    datetime.strptime(event_date, '%Y-%m-%d')
        # event_timeFormat   =    datetime.strptime(event_time, '%H:%M')

        if (sid==""):
            eventFormSave       =   Event(event_name=event_name,
                                        event_type=event_type, 
                                        event_date=event_dateFormat,
                                        event_time=event_time,
                                        user_id=user_id,
                                        user_name=user_name)
        else:        
            eventFormSave       =   Event(id=sid,
                                        event_name=event_name,
                                        event_type=event_type, 
                                        event_date=event_dateFormat,
                                        event_time=event_time,
                                        )

        eventFormSave.save()

        new_event_data  =   Event.objects.values()
        event_data      =   list(new_event_data)
        return JsonResponse ({'event_data': event_data})

@csrf_exempt      
@login_required(login_url= '/users/login')
def delete (request):  
    if request.method   ==  'POST':
        id = request.POST.get('sid')
        event = Event.objects.get(pk=id)
        event.delete()
        return JsonResponse({'status' : 1})
    else:
        return JsonResponse({'status' : 0})

@csrf_exempt      
@login_required(login_url= '/users/login')
def edit (request):  
    if request.method   ==  'POST':
        id      = request.POST.get('sid')
        event   = Event.objects.get(pk=id)

        event_data  =   {
            'id'                : event.id,
            'event_name'        : event.event_name,
            'event_type'        : event.event_type,
            'event_date'        : event.event_date,
            'event_time'        : event.event_time,
            'event_setupDate'   : event.event_setupDate

        }
        return JsonResponse (event_data)


@csrf_exempt      
@login_required(login_url= '/users/login')
def eventpage (request, eid):    
    event   = Event.objects.get(pk=eid)
    
    return render(request, 'event/eventsetup.html', {'event': event})


@csrf_exempt      
@login_required(login_url= '/users/login')
def eventpagejq (request):
    if request.method   ==  'POST':
        id      = request.POST.get('eid')
        # event   = Event.objects.get(pk=id)  
        eventid = Key_var.objects.get(eventcaption="Event")  
        eventid.eventid = id
        eventid.save()
        return JsonResponse ({'status' : 1, 'evid': id})
    else:
        return JsonResponse ({'status' : 0})

@csrf_exempt      
@login_required(login_url= '/users/login')
def eventpagesetup (request): 
    getevent    = Key_var.objects.get(eventcaption="Event") 
    eventid     = getevent.eventid
    event       = Event.objects.get(pk=eventid)

    return render(request, 'event/eventsetup.html', {'event': event})

@csrf_exempt      
@login_required(login_url= '/users/login')
def saveditpos (request): 
    if request.method   ==  'POST':
        sid             =   request.POST.get('posid')
        eventId         = request.POST.get('eventId')
        PosName         = request.POST.get('PosName')
        PosVac          = request.POST.get('PosVac')
        NewPosition     = request.POST.get('NewPosition')

        if NewPosition:
            positions     =   Event_positions(eventid=eventId,
                                    position=PosName, 
                                    avail_seats=PosVac)

        
        positions.save()

        new_event_data  =   Event_positions.objects.values()
        pos_data        =   list(new_event_data)

        return JsonResponse ({'pos_data': pos_data})

        
                                    
        

templates/event/eventsetup.html
{% extends 'base.html' %}

{% block title %}Evoting System{% endblock %}

{% block content %} 
<div class="container-fluid">
    <!-- <h1 class="text-center alert alert-danger">{{event.event_name}}</h1> -->
    <h1 class="text-center alert alert-primary">{{event.event_name}} | {{event.id}}</h1>
    <div class="row">
        <div class="col-lg-5"></div>
        <div class="col-lg-2">
            <!-- <input type="button" value="Add Position" class="btn btn-primary " style="width: 150px;" data-sid="{{eventList.id}}"> -->
        </div><div class="col-lg-5"></div>
    </div>

</div>  

<div class="pop-pos">    
    <button type="button" id = "addpos" class="button btn-primary "> Add Position </button>
</div>

<tbody id='avail-pos'>    

</tbody>
<div class="popup">
    <div class="popup-content">
        <img src="/users/media/profile_pic/close-icon100x100.png" class = "close"  alt="Close">
        <h3 class="text-center pop-title">Add Position</h3>
        <input type="text" class="txtpos" placeholder="Position">
        <input type="text" class="txtvacant" placeholder="Vacant">
        <button type="button" id="btnsave" class="button">Save</button>
    </div>

</div>
<script> 
    $(document).ready(function(){
        let NumTrue=true;
        let NewPosition=true;

        $("#addpos").on("click", function(){
            NewPosition=true; 
            $(".popup").css({display: 'flex'});

        });
        $(".close").on("click", function(){
            $(".popup").css('display', 'none');
            $(".txtvacant").val("");
            $(".txtpos").val("");
        })

        $("#btnsave").on("click", function(){
            if ($.trim($(".txtpos").val())=="" ){
                alert("Please input position")
            }

            else if ($.trim($(".txtvacant").val())=="" ){
                alert("Please input numeric value in vacant position")
            }

            else if  ($.isNumeric($.trim($(".txtvacant").val()))==false){
                alert("Please input numeric value in vacant position")
            }

            let sid = "{{event.id}}";
            let PosName = $.trim($(".txtpos").val());
            let PosVac  = $.trim($(".txtvacant").val());

            $(".popup").css({display: 'none'});

            posData = {
                eventId:sid,
                PosName:PosName,
                PosVac:PosVac,
                NewPosition:NewPosition
            }

            $.ajax({

                url: "{% url 'event:saveditpos' %}",
                    method:'POST',
                    data: posData,
                    success: function(data) {
                        console.log(data);
                        pos_data = data.pos_data
                    }
            })
               
        });
    });
</script>

{% endblock %}

templates/event/index.html
{% extends 'base.html' %}

{% block title %}Evoting System{% endblock %}

{% block content %} 
<div class="container-fluid">
    <h1 class="text-center alert alert-danger">EVENTS MODULE</h1>
    <div class="row">
        <div class="col-lg-2">
            <h4 class="text-center alert alert-info">Event</h4>
            <form action="" method="">
                {% csrf_token %}
                    <input type="hidden" name="eventpid" id="eventpid" />
                    <input type="hidden" name="user_id" value ={{user.id}} id="user_id" />
                    <input type="hidden" name="user_name" value ={{user.user_name}} id="user_name" />
                {{ form.as_p }}
                <input type = 'button' class = "btn btn-success" value="Submit" id="btn-save-event">
            </form>
        </div>
        <div class="col-lg-10">
            <h4 class="text-center alert alert-info">List of events</h4>
            {% if eventLists %}
                <table class = "table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Event(s)</th>
                            <th scope="col">Type</th>
                            <th scope="col">Date</th>
                            <th scope="col">Time</th>
                            <th scope="col">Setup Date</th>
                            <!-- <th scope="col">Setup By</th> -->
                            <th scope="col" class = "text-center">Actions</th>
                            
                        </tr>
                    </thead >
                    <tbody id='tbody'>                       

                            {% for eventList in eventLists %}
                            <tr>
                                <td>{{eventList.id}}</td>
                                
                                <td> <a href="{% url 'event:eventpage' eventList.id %}" id= "{{eventList.id}}" >{{eventList.event_name}}</a></td>
                                <td>{{eventList.event_type}}</td>
                                <td>{{eventList.event_date|date:'Y-m-d'}}</td>
                                <td>{{eventList.event_time|date:'H:i'}}</td>
                                <td>{{eventList.event_setupDate|date:'Y-m-d'}}</td>
                                <!-- <td>{{eventList.user_name}}</td> -->
                                <td class = "text-center">
                                    <input type="button" value="Edit" class="btn btn-warning btn-sm btn-edit-event" 
                                            style="width: 70px;" data-sid="{{eventList.id}}">  
                                    <input type="button" value="Delete" class="btn btn-danger btn-sm btn-del-event" 
                                            style="width: 70px;" data-sid="{{eventList.id}}"> 
                                </td>
                            </tr>
                            {% endfor %}

            {% else %}
                <p>No Record Yet</p>
            {% endif %}
                    </tbody>
                </table>
        </div>
        <!-- <div class="col-sm-1"></div> -->
    </div>

</div>  

<script>
    $(document).ready(function(){
    //    var current_user :{request.user}
        $('#btn-save-event').on("click", function(){
            let sid         = $("#eventpid").val();
            let event_name  = $("#event_name").val();
            let event_type  = $("#event_type").val();
            let event_date  = $("#event_date").val();
            let event_time  = $("#event_time").val();
            let user_id     = $("#user_id").val();
            let user_name   = $("#user_name").val();
            outputEventData = "";
            
            if ($.trim(event_name) =="") {
                console.log("Please input event name");
            } else if ($.trim(event_type) =="") {
                console.log("Please input event type");
            } else if ($.trim(event_date) =="") {
                console.log("Please input event date");
            } else if ($.trim(event_time) =="") {
                console.log("Please input event time");
            } else {
                myEventData = {eventpid   : sid,
                               event_name : event_name, 
                               event_type : event_type,
                               event_date : event_date,
                               event_time : event_time,
                               user_id    : parseInt(user_id),
                               user_name  : user_name
                            }
                console.log(myEventData)
                $.ajax({
                    url: "{% url 'event:saveditevent' %}",
                    method:'POST',
                    data: myEventData,
                    success: function(data) {
                        console.log(data);
                        event_data = data.event_data
                        $("#event_name").val("");
                        
                        for(i=0; i<event_data.length; i++){
                            let eid = event_data[i].id
                            let streid = eid.toString();
                            outputEventData+="<tr><td>" + event_data[i].id +                            
                                
                                "</td><td> <div " + "eid='" + event_data[i].id +"'" + " class ='esetup' style='cursor: pointer; color:blue;'>" + event_data[i].event_name + "</div>" +
                                
                                "</td><td>" + event_data[i].event_type +
                                "</td><td>" + event_data[i].event_date +
                                "</td><td>" + event_data[i].event_time.substr(0, 5) +
                                
                                "</td><td>" + event_data[i].event_setupDate +
                                
                                "</td><td class = 'text-center'> <input type='button' value='Edit' class='btn btn-warning btn-sm btn-edit-event' style='width: 70px;' data-sid=" + event_data[i].id + "> <input type='button' value='Delete' class='btn btn-danger btn-sm btn-del-event' style='width: 70px;' data-sid=" + event_data[i].id + ">"
                        }
                        $('#tbody').html(outputEventData);
                        $("#eventpid").val("");
                        $('form')[0].reset();
                        

                    }
                });
            }

            
        });
        
        //Delete
        $('#tbody').on("click", ".btn-del-event", function (){
            console.log("Delete Clicked");
            let id = $(this).attr("data-sid");
            eventData = {sid:id};
            mythis = $(this);

            $.ajax({
                url: "{% url 'event:delete' %}",
                method:'POST',
                data: eventData,
                success: function(data) {
                    console.log(data);
                    if (data.status == 1){
                        console.log('record deleted');
                        $(mythis).closest("tr").fadeOut();
                    }
                    else if (data.status == 0){
                        console.log('delete failed');               
                    }
                }
            });
        });

        //Edit
        $('#tbody').on("click", ".btn-edit-event", function (){
            console.log("Edit Clicked");
            let id = $(this).attr("data-sid");
            eventData = {sid:id};
            mythis = $(this);

            $.ajax({
                url: "{% url 'event:edit' %}",
                method:'POST',
                data: eventData,
                success: function(data) {
                    console.log(data);

                    $("#eventpid").val(data.id);
                    $("#event_name").val(data.event_name);
                    $("#event_type").val(data.event_type);
                    $("#event_date").val(data.event_date);
                    $("#event_time").val(data.event_time);
                    
                }
            });
        });
        //Edit

        //esetup
        $('#tbody').on("click", ".esetup", function (){
            console.log("eSetup Clicked");
            let id = $(this).attr("eid");
            eventData = {eid:id};
            mythis = $(this);

            $.ajax({
                url: "{% url 'event:eventpagejq' %}",
                method:'POST',
                data: eventData,
                success: function(data) {
                    // console.log(data);
                    var eventid = parseInt(data.evid);
                    // console.log(eventid);
                    if (data.status == 1) {
                        console.log(eventid);
                        window.location = "{% url 'event:eventpagesetup' %}";
                    }
                    
                    
                }
            });
        });
        //esetup

        
                   
    });
</script>

{% endblock %}

templates/event/indexbackup.html
{% extends 'base.html' %}

{% block title %} Evoting System{% endblock %}

{% block content %} 
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">

            <h4 class="text-center alert alert-info">Event Setup</h4>
                <form action="" method="">
                    {% csrf_token %}
                        <!-- <input type="hidden" name="empid" id="empid" /> -->
                    {{ form.as_p }}
                    <input type = 'button' id = "btn-save-event" class = "btn btn-success" value="Submit" id="btnsave">
                </form>

        </div>
        <div class="col-sm-4"></div>

    </div>
</div>

<script>
    $(document).ready(function(){
        $('#btn-save-event').on("click", function(){
            $.ajax({
            url: "{% url 'edit' %}",
            method:'POST',
            data: mydata,
            success: function(data) {
            // console.log(data);
            
        }
    });
        });
                   
    });
</script>

{% endblock %}