aws/urls.py
from django.contrib import admin
from django.urls import include, path, re_path as url
from django.views.static import serve
from django.conf import settings
from . import views

app_name = 'aws'

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path ('', views.index, name='index'),
    path ('addaccount/', views.addaccount, name='addaccount'),
    path ('processaddaccount/', views.processaddaccount, name='processaddaccount'),
    path ('awsaccounts/', views.awsaccounts, name='awsaccounts'),
    path ('<int:serverid>/startreserver/', views.startreserver, name='startreserver'),
    path ('<int:serverid>/stopserver/', views.stopserver, name='stopserver'),
    path ('<str:instanceid>/instancerdp/', views.instancerdp, name='instancerdp'),
    path ('ubuntuservers/', views.ubuntuservers, name='ubuntuservers'),
    path ('<int:serverid>/startreubuntuservers/', views.startreubuntuservers, name='startreubuntuservers'),
    path ('<int:serverid>/stopubuntuservers/', views.stopubuntuservers, name='stopubuntuservers'),
    path ('windowsservers/', views.windowsservers, name='windowsservers'),
    path ('<int:serverid>/startrewindowsservers/', views.startrewindowsservers, name='startrewindowsservers'),
    path ('<int:serverid>/stopwindowsservers/', views.stopwindowsservers, name='stopwindowsservers'),    
    #ubuntuservers page

    path ('<str:area>/<str:action>/startareaservers/', views.startareaservers, name='startareaservers'),
    path ('<int:stopstart>/ssallwindowsservers/', views.ssallwindowsservers, name='ssallwindowsservers'),
    # path ('<int:serverid>/winrdpaccess/', views.winrdpaccess, name='winrdpaccess'),
]

clients/urls.py
from django.urls import path, re_path as url
from django.views.static import serve
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'clients'
urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('', views.index, name='index'),
    path('search',views.search, name='search'),
    path('addclient',views.addclient, name='addclient'),
    path('cancelledclient',views.cancelledclient, name='cancelledclient'),
    path('processaddclient',views.processaddclient, name='processaddclient'),
    path('<int:profile_id>/clientdetail/',views.clientdetail, name='clientdetail'),
    path('<int:profile_id>/cancelledclientdetail/',views.cancelledclientdetail, name='cancelledclientdetail'),
    # path('<int:profile_id>/clientdelete/',views.clientdelete, name='clientdelete'),
    path('<int:profile_id>/clientdisable/',views.clientdisable, name='clientdisable'),
    path('<int:profile_id>/clientedit/',views.clientedit, name='clientedit'),
    path('<int:profile_id>/processclientedit/',views.processclientedit, name='processclientedit'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kmsystem/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path ('', views.index, name='index'),
    path ('event/', include ('event.urls')),
    path ('aws/', include ('aws.urls')),
    path ('mmaptsp2/', include ('mmaptsp2.urls')),
    path ('clients/', include ('clients.urls')),
    path ('users/', include ('users.urls')),
    path('admin/', admin.site.urls),   
    
]

mmaptsp2/urls.py
from django.urls import path, re_path as url
from django.views.static import serve
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'mmaptsp2'
urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('', views.index, name='index'),    
    path('cancelledmmap', views.cancelledmmap, name='cancelledmmap'),   
    path('loadclient', views.loadclient, name='loadclient'),
    path('search', views.search, name='search'),
    path('searchclient',views.searchclient, name='searchclient'),
    path('<int:profile_id>/addmmap', views.addmmap, name='addmmap'),
    path('<int:profile_id>/mmapdetail/',views.mmapdetail, name='mmapdetail'),
    path('<int:mmap_id>/mmapedit/',views.mmapedit, name='mmapedit'),
    # path('<int:mmap_id>/mmapdelete/',views.mmapdelete, name='mmapdelete'),
    path('<int:mmap_id>/mmapcancel/',views.mmapcancel, name='mmapcancel'),
    path('<int:mmap_id>/processmmapedit/',views.processmmapedit, name='processmmapedit'),
    path('processaddmmap', views.processaddmmap, name='processaddmmap'),
    path('patchbenmmapid', views.patchbenmmapid, name='patchbenmmapid'),
    path('patchsccn', views.patchsccn, name='patchsccn'),
    path('filterby', views.filterby, name='filterby'),
    path('processfilterby', views.processfilterby, name='processfilterby'),
    path('allexpcurrent/<str:exporcurrent>/', views.allexpcurrent, name='allexpcurrent'),
    path('<int:profile_id>/mmapexpdetail/',views.mmapexpdetail, name='mmapexpdetail'),
    path('allexpcurrentexportdata/<str:exporttype>/', views.allexpcurrentexportdata, name='allexpcurrentexportdata'),
    path('exportdata/<str:exporttype>',views.exportdata, name='exportdata'),
    path('csv-upload/',views.csv_upload, name='csv_upload'),
    path('mmapclaim/',views.mmapclaim, name='mmapclaim'),
    path('newrenewstatus/',views.newrenewstatus, name='newrenewstatus'),
    path('<int:profile_id>/mmapdetailpdf/',views.mmapdetailpdf, name='mmapdetailpdf'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mmaptsp2/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from django.core.paginator import Paginator
from django.db.models import Q
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required, permission_required
from .models import Mmap, Beneficiary, Branchcode, Sccn
from clients.models import Client, Clientaccountcode
from datetime import datetime, timedelta
import csv, io
import xlwt
from django.contrib import messages
import json


# for PDF
from django.template.loader import render_to_string
from weasyprint import HTML
import tempfile
from django.db.models import Sum



@login_required(login_url= '/users/login')
def index(request):
    user = request.user
    mmap_list           =       Mmap.objects.filter(is_canceled=False).order_by('mmap_expired')

    if user.can_selectbranch==False:
        mmap_list           =       mmap_list.filter(mmap_branch=user.user_branch)
    
    mmap_expired        =       mmap_list.filter(expired_status="True")
    mmap_current        =       mmap_list.filter(expired_status="False")
    # mmap_final          =       mmap_current.all().order_by('mmap_expired')
    paginator           =       Paginator(mmap_current, 10) 
    page_number         =       request.GET.get('page') 
    mmap_final          =       paginator.get_page(page_number)
    context             =       {'page_obj': mmap_final, 'expcount': mmap_expired.all().count(), 
                                'currentcount':mmap_current.all().count(), 'total': mmap_list.all().count()}
    return render (request, 'mmaptsp2/index.html', context)


    # if user.can_selectbranch==False:
    #     mmap_list           =       Mmap.objects.filter(mmap_branch=user.user_branch).order_by('mmap_expired')
    #     mmap_expired        =       mmap_list.filter(expired_status="True")
    #     mmap_current        =       mmap_list.filter(expired_status="False")
    #     # mmap_final          =       mmap_current.all().order_by('mmap_expired')
    #     paginator           =       Paginator(mmap_current, 10) 
    #     page_number         =       request.GET.get('page') 
    #     mmap_final          =       paginator.get_page(page_number)
    #     context             =       {'page_obj': mmap_final, 'expcount': mmap_expired.all().count(), 
    #                                 'currentcount':mmap_current.all().count(), 'total': mmap_list.all().count()}
    #     return render (request, 'mmaptsp2/index.html', context)

    # else:

    #     mmap_list           =       Mmap.objects.all().order_by('mmap_expired')
    #     mmap_expired        =       mmap_list.filter(expired_status="True")
    #     mmap_current        =       mmap_list.filter(expired_status="False")
    #     # mmap_final          =       mmap_current.all().order_by('mmap_expired')
    #     paginator           =       Paginator(mmap_current, 10)
    #     page_number         =       request.GET.get('page')
    #     mmap_final           =       paginator.get_page(page_number)
    #     context             =       {'page_obj': mmap_final,'expcount': mmap_expired.all().count(), 
    #                                 'currentcount':mmap_current.all().count(), 'total': mmap_list.all().count() }
    #     return render (request, 'mmaptsp2/index.html', context)

    # mmap_list = Mmap.objects.all().order_by('mmap_expired')
    # mmap_list = Mmap.objects.filter(expired_status="False")
    # paginator = Paginator(mmap_list, 10)    
    # page_number = request.GET.get('page')
    # mmap_list = paginator.get_page(page_number)
    # return render (request, 'mmaptsp2/index.html', {'page_obj': mmap_list})

@login_required(login_url= '/users/login')
def search(request):
    user = request.user
    term = request.GET.get('search', '')
    mmapraw         =       Mmap.objects.filter(expired_status="False").order_by('mmap_expired')
    mmap_list       =       mmapraw.filter(Q(mmap_name__icontains=term))

    if user.can_selectbranch==False:
        mmap_list   =       mmap_list.filter(mmap_branch=user.user_branch)

    paginator       =       Paginator(mmap_list, 10)    
    page_number     =       request.GET.get('page')
    mmap_list       =       paginator.get_page(page_number)
    return render (request, 'mmaptsp2/index.html', {'page_obj': mmap_list, 'term':term})


# def mmapdelete(request, mmap_id):
    # cycle           =       request.POST.get('client_cycle')
    # mmap        =       Mmap.objects.get(id=mmap_id)
    # Mmap.objects.filter(id=mmap_id).delete()    
    # Beneficiary.objects.get(mmapid=mmap_id).delete()
    # clientID.delete()
    
    # return HttpResponseRedirect('/mmaptsp2')
@login_required(login_url= '/users/login')
def mmapcancel(request, mmap_id):    
    mmap                    =   Mmap.objects.get(id=mmap_id)
    mmap.is_canceled        =   True
    mmap.expired_status     =   True
    mmap.save()
    return HttpResponseRedirect('/mmaptsp2')


@login_required(login_url= '/users/login')
def cancelledmmap(request):    
    user = user = request.user
    mmap_list =   Mmap.objects.filter(is_canceled=True)

    if user.can_selectbranch == False:
        mmap_list   =   mmap_list.filter(mmap_branch=user.user_branch)
    
    return render (request, 'mmaptsp2/cancelledmmap.html', {'page_obj': mmap_list})

@login_required(login_url= '/users/login')
def loadclient(request):
    user            =       request.user
    client_list     =       Client.objects.filter(client_isdisabled=False).order_by('-id')
    if user.can_selectbranch==False:
        client_list   =       client_list.filter(client_branch=user.user_branch)
    # client_list     =       Client.objects.filter(client_branch=user.user_branch).order_by('-id')
    paginator       =       Paginator(client_list, 10)    
    page_number     =       request.GET.get('page')
    client_list     =       paginator.get_page(page_number)
    return render (request, 'mmaptsp2/loadsearchclient.html', {'page_obj': client_list})

@login_required(login_url= '/users/login')
def searchclient(request):
    term = request.GET.get('search', '').strip()
    user = request.user

    activeClients = Client.objects.filter(client_isdisabled=False)

    if user.can_selectbranch == False:
        activeClients   =   activeClients.filter(client_branch=user.user_branch)
    # client_filter_branch    =   Client.objects.filter(client_branch=user.user_branch)
    client_list = activeClients.filter(Q(client_fname__icontains=term) | Q(client_lname__icontains=term)).order_by('-id')

    if term == "":
        paginator = Paginator(client_list, 5)    
        page_number = request.GET.get('page')
        client_list = paginator.get_page(page_number)
    return render (request, 'mmaptsp2/loadsearchclient.html', {'page_obj': client_list})


@login_required(login_url= '/users/login')
def addmmap(request, profile_id):    
    mmaptype =""

    client = Client.objects.get(pk=profile_id)       
    d_o_b = int((datetime.now().date() - client.client_dob).days / 365.25)

    if (d_o_b < 18):
        mmaptype = "N/A"
    elif (d_o_b < 65):
        mmaptype = "18-64"    
    elif d_o_b < 70 :
        mmaptype = "65-69"
    elif d_o_b > 70 :
        mmaptype = "70-Up"
    # else:
    #     mmaptype = "N/A"

    cycle= int(client.client_cycle) + 1
    context= {'client': client, 
                'd_o_b': str(d_o_b),
                'cycle':cycle,
                "mmaptype":mmaptype}
    return render(request, 'mmaptsp2/add.html', context) #with or w/o str it still working

@login_required(login_url= '/users/login')
def processaddmmap(request):

    hidclientid = request.POST.get('hidclientid')
    client = Client.objects.get(pk=hidclientid) 
    clientid=client.id
    client_code = client.client_code
    clientimg = client.client_image
    mmap_name = client.client_fname + " " + client.client_mname + " " + client.client_lname
    mmap_sex = client.client_gender
    mmap_age = int((datetime.now().date() - client.client_dob).days / 365.25)
    mmap_branch = client.client_branch
    mmap_address = client.client_address
    mmap_dob = client.client_dob
    client_cycle = int(client.client_cycle) + 1

    client.client_cycle = client_cycle
    client.save()
    
    if request.FILES.get('mmap_form_fimage'):
        mmap_form_fimage = request.FILES.get('mmap_form_fimage')
    else:
        mmap_form_fimage='mmaptsp2_pic/default_image.png'

    if request.FILES.get('mmap_form_bimage'):
        mmap_form_bimage = request.FILES.get('mmap_form_bimage')
    else:
        mmap_form_bimage='mmaptsp2_pic/default_image.png'

    mmap_setupdate = request.POST.get('mmap_setupdate')
    recuited_by = request.POST.get('recuited_by')        
    processed_by = request.POST.get('processed_by')
    processed_des = request.POST.get('processed_des')
    processed_date = request.POST.get('processed_date')
    checked_by = request.POST.get('checked_by')
    checked_des = request.POST.get('checked_des')
    checked_date = request.POST.get('checked_date')
    approved_by = request.POST.get('approved_by')
    approved_des = request.POST.get('approved_des')
    approved_date = request.POST.get('approved_date')
    mmap_type = request.POST.get('mmap_type')
    # mmap_form_fimage = request.POST.get('mmap_form_fimage')
    # mmap_form_bimage = request.POST.get('mmap_form_bimage')

    startDate = datetime.strptime(mmap_setupdate, '%Y-%m-%d')
    add1Year = datetime (startDate.year + 1, startDate.month, startDate.day)
    mmap_expired= add1Year #+ datetime.timedelta(days=1)
    #mmap_expired = mmap_setupdate + datetime.year(1)
    #mmap_expired = mmap_setupdate.days + 365.25
   

    # getclientcodes=get_object_or_404(Clientaccountcode, branch=client_branch)
    

templates/mmaptsp2/csv_upload.html
{% extends 'base.html' %}

{% block title %} Users List {% endblock %}

{% block content %} 

{% if messages %}
    {% for message in messages %}
        <div>
            <strong>{{message|safe}}</strong>
        </div>
    {% endfor %}
{% else %}
{{order}}
<form  method="POST" enctype="multipart/form-data" action="{% url 'mmaptsp2:csv_upload' %}" >
    {% csrf_token %}
    <label>Upload file</label>
    <input type="file" name="file">
    <p>Accept only CSV files</p>
    <button type="submit">Upload</button>

</form>
{% endif %}

{% endblock %}

templates/mmaptsp2/index.html
{% extends 'base.html' %}

{% block title %} Users List {% endblock %}

{% block content %} 


    <p>Current: {{currentcount}}, Exp: {{expcount}}, Total: {{total}}</p>
    <form action="{% url 'mmaptsp2:search' %}" method="GET">
        <div class="input-group">
            <input type="text" class="form-control" name="search" value= "{{term}}" placeholder="Search">
            <div class="input-group-append">
                <button type="submit" class="btn btn-success">Search</button>
            </div>
        </div>
    </form>

    <h3 class = "text-center mb-4 mt-4" >Registered Members</h3>

    {% if page_obj %}
        <div class="table-responsive">
            <table class = "table table-bordered table-striped table-hover table-sm">
                <thead class = "thead-light">
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>DATE REG</th>
                        <th>DATE EXP</th>
                        <th>DATE ENCODED</th>
                        <th>AGE</th>
                        <th>SCCN</th>
                        <th>BCODE</th>
                        <th>CYCLE</th>
                        <th>Branch</th>
                    </tr>     
                </thead>

                <tbody>
                    {% for mmap in page_obj %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'mmaptsp2:mmapdetail' mmap.id %}">
                                {{ mmap.mmap_name }}
                            </a>
                        </td>
                        <td>{{ mmap.mmap_setupdate|date:'Y-m-d' }}</td>
                        <td>{{ mmap.mmap_expired|date:'Y-m-d' }}</td>
                        <td>{{ mmap.mmap_encodedate|date:'Y-m-d' }}</td>
                        <td>{{ mmap.mmap_age }}</td>
                        <td>{{ mmap.mmapservicecentercontrolno }}</td>
                        <td>{{ mmap.mmapbcode }}</td>
                        <td>{{ mmap.client_cycle }}</td>
                        <td>{{ mmap.mmap_branch }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <ul class="pagination">

                {% if page_obj.has_previous %}
                    <li class="page-item"><a href="?page=1" class="page-link" >&laquo; First</a></li>
                    <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a></li>
                {% endif %}

                {% if page_obj.has_next %}
                    <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a></li>
                    <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">&raquo;Last</a></li>
                {% endif %}


            </ul>

        </div>
    
    {% else %}
    <p>No records available</p>

    {% endif %}
{% endblock %}

templates/mmaptsp2/mmapdetail.html
{% extends 'base.html' %}

{% block title %} MMAP Detail {% endblock %}

{% block content %} 



{% if error_message %}
    <p class = "alert alert-danger">
        <strong>{{ error_message }}</strong>
    </p>

{% endif %}

<!-- row Start --->
        <div class ="row border border-light shadow-sm rounded mt-2 mb-2" >

<!-- col-lg-4  Start --->
            <div class="col-lg-4">
                <div class="form-group">
                    <label>Member's Name</label>
                    <input type="text" name="mmap_name" id="mmap_name" class="form-control" value="{{mmap.mmap_name}}" readonly>
                </div>    
                
                <div class="form-group">
                    <label>Branch</label>
                    <input type="text" name="mmap_branch" id="mmap_branch" class="form-control" value="{{mmap.mmap_branch}}" readonly>
                </div>  

                <div class="form-group">
                    <div class = "row">
                        <div class="col-lg-4">
                            <label>MMAP Type</label>
                            <input type="text" name="mmap_type" id="mmap_type" class="form-control" value="{{mmap.mmap_type}}" readonly>
                        </div>
                        <div class="col-lg-8">
                            <label>Date Registered</label>
                            <input type="date" name="mmap_setupdate" id="mmap_setupdate" class="form-control" value="{{mmap.mmap_setupdate|date:'Y-m-d'}}" readonly>
                        </div>                        
                    </div>
                </div> 
                      


            </div> <!-- col-lg-4 End --->
                
<!-- col-lg-4 Start --->
            <div class="col-lg-4">
                <div class="form-group">
                    <div class = "row">
                        <div class="col-lg-6">
                            <label>Client Code</label>
                            <input type="text" name="clientid" id="clientid" class="form-control" value="{{mmap.client_code}}" readonly>
                            <!--
                                <input type="hidden" name="hidclientid" id="hidclientid" class="form-control" value="{{mmap.clientid}}">
                             -->
                        </div>   
                        <div class="col-lg-6">
                            <label>Sex</label>
                            <input type="text" name="mmap_sex" id="mmap_sex" class="form-control" value="{{mmap.mmap_sex}}" readonly >
                        </div>
                    </div>
                </div>
                
                <div class="form-group">
                    <label>Date of Birth</label>
                    <input type="date" name="mmap_dob" id="mmap_dob" class="form-control" value="{{mmap.mmap_dob|date:'Y-m-d' }}"  readonly>
                </div>

                <div class ="row mt-3 mb-2">
                    <div class="col-lg-9">
                        <div class="form-group">
                            <label>Recruited by</label>
                            <input type="text" name="recuited_by" id="recuited_by" class="form-control" value="{{mmap.recuited_by}}" readonly>
                        </div> 
                    </div>   
                    <div class="col-lg-3">
                        <div class="form-group">
                            <label>Cycle</label>
                            <input type="text" class="form-control" value="{{ mmap.client_cycle }}" readonly >
                            <input type="hidden" name="client_cycle" id="client_cycle" class="form-control" value="{{ mmap.client_cycle }}" readonly >
                        </div>   
                    </div>
                </div>                            
            

            </div> <!-- col-lg-4 End --->

<!-- col-lg-4 Start --->
            <div class="col-lg-4">
                <div class="form-group">
                    <label>Age</label>
                    <input type="text" name="mmap_age" id="mmap_age" class="form-control" value="{{mmap.mmap_age}}" readonly>
                </div>   
                
                <div class="form-group">
                    <label>Address</label>
                    <input type="text" name="mmap_address" id="mmap_address" class="form-control" value="{{mmap.mmap_address}}" readonly>
                </div>

                <div class ="row mt-3 mb-2"> 
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label>Front Form</label>
                            <!-- <input type="file" name="mmap_form_fimage" id="mmap_form_fimage" value="{{ mmap.mmap_form_fimage }}"/> -->
                            <label><a href="/mmaptsp2/media/{{ mmap.mmap_form_fimage }}" target="_blank">View Image</a>
                            <label>
                        </div> 
                        <div class="form-group">
                            <label>Back Form</label>
                            <!-- <input type="file" name="mmap_form_bimage" id="mmap_form_bimage" value="{{ mmap.mmap_form_bimage }}" />   -->
                            <label><a href="/mmaptsp2/media/{{ mmap.mmap_form_bimage }}" target="_blank">View Image</a>
                                <label>                      
                        </div>   
                    </div>             
                </div> 


            </div> <!-- col-lg-4 End --->

        </div> <!-- row End --->

        <div class ="row border border-light shadow-sm rounded mt-3 mb-2"> <!-- row Benificiary Start --->
            <div class="col-lg-4">
                <div class="form-group">
                    <label>Name of Dependents/Beneficiaries</label>
                    <input type="text" name="ben1" id="ben1" class="form-control" value="{{beneficiary.ben1}}"  readonly>
                </div> 

                <div class="form-group">
                    <input type="text" name="ben2" id="ben2" class="form-control"  value="{{beneficiary.ben2}}" readonly>
                </div> 

                <div class="form-group">
                    <input type="text" name="ben3" id="ben3" class="form-control"  value="{{beneficiary.ben3}}"  readonly>
                </div> 

            </div>
            <div class="col-lg-4">            

                <div class="form-group">
                    <label>Date of Birth</label>
                    <input type="date" name="ben1_dob" id="ben1_dob" class="form-control"   value="{{beneficiary.ben1_dob|date:'Y-m-d'}}" readonly>
                </div> 

                <div class="form-group">
                    <input type="date" name="ben2_dob" id="ben2_dob" class="form-control"  value="{{beneficiary.ben2_dob|date:'Y-m-d'}}" readonly>
                </div> 

                <div class="form-group">
                    <input type="date" name="ben3_dob" id="ben3_dob" class="form-control"  value="{{beneficiary.ben3_dob|date:'Y-m-d'}}" readonly>
                </div> 
            </div>
            <div class="col-lg-4">
                <div class="form-group">
                    <label>Relationship</label>
                    <input type="text" name="ben1_rel" id="ben1_rel" class="form-control" value="{{beneficiary.ben1_rel}}" readonly >
                </div>
                <div class="form-group">
                    <input type="text" name="ben2_rel" id="ben2_rel" class="form-control" value="{{beneficiary.ben2_rel}}" readonly>
                </div>
                <div class="form-group">
                    <input type="text" name="ben3_rel" id="ben3_rel" class="form-control" value="{{beneficiary.ben3_rel}}" readonly>
                </div>
                
            </div>
        </div> <!-- row Benificiary End --->


        <div class ="row border border-light shadow-sm rounded mt-3 mb-2"> <!-- row Start --->
            <div class="col-lg-4">
                <div class="form-group">
                    <label>Processed by</label>
                    <input type="text" name="processed_by" id="processed_by" value="{{mmap.processed_by}}" class="form-control" readonly>
                </div> 

                <div class="form-group">
                    <label>Checked by</label>
                    <input type="text" name="checked_by" id="checked_by" value="{{mmap.checked_by}}" class="form-control" readonly>
                </div> 

                <div class="form-group">
                    <label>Approved by</label>
                    <input type="text" name="approved_by" id="approved_by" value="{{mmap.approved_by}}" class="form-control" readonly>
                </div> 

                <div class="form-group">
                    <label>Branch Control Number</label>
                    <input type="text" name="branch_control_number" id="branch_control_number" value="{{mmap.mmapservicecentercontrolno}}" class="form-control" readonly>
                </div>

            </div>
            <div class="col-lg-4">            

                <div class="form-group">
                    <label>Designation</label>
                    <input type="text" name="processed_des" id="processed_des" value="{{mmap.processed_des}}" class="form-control" readonly> 
                </div> 

                <div class="form-group">
                    <label>Designation</label>
                    <input type="text" name="checked_des" id="checked_des" value="{{mmap.checked_des}}" class="form-control" readonly>
                </div> 

                <div class="form-group">
                    <label>Designation</label>
                    <input type="text" name="approved_des" id="approved_des" value="{{mmap.approved_des}}" class="form-control" readonly>
                </div> 
                <div class="form-group">
                    <label>Date|Time Encoded</label>
                    <input type="text" name="encodedate}" id="encodedate}" value="{{mmap.mmap_encodedate}}" class="form-control" readonly>
                </div> 
                <div class="btn-group d-flex" role="group">        
                    {% if user.can_editclient %}
                        <a href="{% url 'mmaptsp2:mmapcancel' mmap.id %}" class="btn btn-sm btn-danger" style="width:25%;">Cancel</a>
                        <a href="{% url 'mmaptsp2:mmapedit' mmap.id %}" class="btn btn-sm btn-info" style="width:25%;" >Edit</a>
                    {% endif %}
                        <a href="{% url 'mmaptsp2:index' %}" class="btn btn-sm btn-success" style="width:25%;">Return</a>   
                        <a href="{% url 'mmaptsp2:mmapdetailpdf' mmap.id %}" class="btn btn-sm btn-info" style="width:25%;">Export PDF</a>        
                </div>
            </div>
            <div class="col-lg-4">
                <div class="form-group">
                    <label>Date</label>
                    <input type="date" name="processed_date" id="processed_date" value="{{mmap.processed_date|date:'Y-m-d'}}" class="form-control" readonly>
                </div>
                <div class="form-group">
                    <label>Date</label>
                    <input type="date" name="checked_date" id="checked_date" value="{{mmap.checked_date|date:'Y-m-d'}}" class="form-control" readonly>
                </div>
                <div class="form-group">
                    <label>Date</label>
                    <input type="date" name="approved_date" id="approved_date" value="{{mmap.approved_date|date:'Y-m-d'}}" class="form-control" readonly>
                </div>
                <div class="form-group">
                    <label>Date Expired</label>
                    <input type="date" name="mmap_expired" id="mmap_expired" value="{{mmap.mmap_expired|date:'Y-m-d'}}" class="form-control" readonly>
                </div> 
            </div>
        </div> <!-- row End --->


    
        



   
{% endblock %}