aws/urls.py
from django.contrib import admin
from django.urls import include, path, re_path as url
from django.views.static import serve
from django.conf import settings
from . import views

app_name = 'aws'

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path ('', views.index, name='index'),
    path ('addaccount/', views.addaccount, name='addaccount'),
    path ('processaddaccount/', views.processaddaccount, name='processaddaccount'),
    path ('awsaccounts/', views.awsaccounts, name='awsaccounts'),
    path ('<int:serverid>/startreserver/', views.startreserver, name='startreserver'),
    path ('<int:serverid>/stopserver/', views.stopserver, name='stopserver'),
    path ('<str:instanceid>/instancerdp/', views.instancerdp, name='instancerdp'),
    path ('ubuntuservers/', views.ubuntuservers, name='ubuntuservers'),
    path ('<int:serverid>/startreubuntuservers/', views.startreubuntuservers, name='startreubuntuservers'),
    path ('<int:serverid>/stopubuntuservers/', views.stopubuntuservers, name='stopubuntuservers'),
    path ('windowsservers/', views.windowsservers, name='windowsservers'),
    path ('<int:serverid>/startrewindowsservers/', views.startrewindowsservers, name='startrewindowsservers'),
    path ('<int:serverid>/stopwindowsservers/', views.stopwindowsservers, name='stopwindowsservers'),    
    #ubuntuservers page

    path ('<str:area>/<str:action>/startareaservers/', views.startareaservers, name='startareaservers'),
    path ('<int:stopstart>/ssallwindowsservers/', views.ssallwindowsservers, name='ssallwindowsservers'),
    # path ('<int:serverid>/winrdpaccess/', views.winrdpaccess, name='winrdpaccess'),
]

kmsystem/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path ('', views.index, name='index'),
    path ('event/', include ('event.urls')),
    path ('aws/', include ('aws.urls')),
    path ('mmaptsp2/', include ('mmaptsp2.urls')),
    path ('clients/', include ('clients.urls')),
    path ('users/', include ('users.urls')),
    path('admin/', admin.site.urls),   
    
]

mmaptsp2/urls.py
from django.urls import path, re_path as url
from django.views.static import serve
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'mmaptsp2'
urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('', views.index, name='index'),    
    path('cancelledmmap', views.cancelledmmap, name='cancelledmmap'),   
    path('loadclient', views.loadclient, name='loadclient'),
    path('search', views.search, name='search'),
    path('searchclient',views.searchclient, name='searchclient'),
    path('<int:profile_id>/addmmap', views.addmmap, name='addmmap'),
    path('<int:profile_id>/mmapdetail/',views.mmapdetail, name='mmapdetail'),
    path('<int:mmap_id>/mmapedit/',views.mmapedit, name='mmapedit'),
    # path('<int:mmap_id>/mmapdelete/',views.mmapdelete, name='mmapdelete'),
    path('<int:mmap_id>/mmapcancel/',views.mmapcancel, name='mmapcancel'),
    path('<int:mmap_id>/processmmapedit/',views.processmmapedit, name='processmmapedit'),
    path('processaddmmap', views.processaddmmap, name='processaddmmap'),
    path('patchbenmmapid', views.patchbenmmapid, name='patchbenmmapid'),
    path('patchsccn', views.patchsccn, name='patchsccn'),
    path('filterby', views.filterby, name='filterby'),
    path('processfilterby', views.processfilterby, name='processfilterby'),
    path('allexpcurrent/<str:exporcurrent>/', views.allexpcurrent, name='allexpcurrent'),
    path('<int:profile_id>/mmapexpdetail/',views.mmapexpdetail, name='mmapexpdetail'),
    path('allexpcurrentexportdata/<str:exporttype>/', views.allexpcurrentexportdata, name='allexpcurrentexportdata'),
    path('exportdata/<str:exporttype>',views.exportdata, name='exportdata'),
    path('csv-upload/',views.csv_upload, name='csv_upload'),
    path('mmapclaim/',views.mmapclaim, name='mmapclaim'),
    path('newrenewstatus/',views.newrenewstatus, name='newrenewstatus'),
    path('<int:profile_id>/mmapdetailpdf/',views.mmapdetailpdf, name='mmapdetailpdf'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aws/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone
from django.utils.timezone import now
from django.utils.safestring import mark_safe
import os, random

# Create your models here.

class Awsaccounts(models.Model):
    accountName             = models.CharField(max_length=150, verbose_name='Account Name', blank=True)
    accountID               = models.CharField(max_length=50, verbose_name='Account ID', blank=True)
    accountUser             = models.CharField(max_length=150, verbose_name='Account User', blank=True)
    accessKeyID             = models.CharField(max_length=150, verbose_name='Access Key ID', blank=True)
    secretAccessKey         = models.CharField(max_length=150, verbose_name='Secret Access Key', blank=True)
    region                  = models.CharField(max_length=150, verbose_name='Region', blank=True)

class Aws(models.Model):
    accountName             = models.CharField(max_length=150, verbose_name='Account Name', blank=True)
    accountID               = models.CharField(max_length=50, verbose_name='Account ID', blank=True)
    accountUser             = models.CharField(max_length=150, verbose_name='Account User', blank=True)
    accessKeyID             = models.CharField(max_length=150, verbose_name='Access Key ID', blank=True)
    secretAccessKey         = models.CharField(max_length=150, verbose_name='Secret Access Key', blank=True)
    instanceName            = models.CharField(max_length=150, verbose_name='Instance Name', blank=True)
    instanceID              = models.CharField(max_length=150, verbose_name='Instance ID', blank=True)
    region                  = models.CharField(max_length=150, verbose_name='Region', blank=True)
    serverIP                = models.CharField(max_length=150, verbose_name='Server IP', blank=True)
    database                = models.CharField(max_length=150, verbose_name='Database', blank=True)
    serverType              = models.CharField(max_length=150, verbose_name='Server Type', blank=True)
    setupDate               = models.DateField(verbose_name='Setup Date', default=now)
    area                    = models.CharField(max_length=150, verbose_name='Area', blank=True)
    rdpPass                 = models.CharField(max_length=150, verbose_name='RDP Password', blank=True)


           

aws/views.py
from nturl2path import url2pathname
from this import d
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse, response
from django.core.paginator import Paginator
from django.db.models import Q
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required, permission_required
# from mmaptsp2.models import Mmap, Beneficiary, Branchcode, Sccn
# from mmpaptsp2.models import Client, Clientaccountcode
from .models import Aws, Awsaccounts
from datetime import datetime, timedelta
import boto3
import pyperclip

@login_required(login_url= '/users/login')
def index(request):
    awsUbuntuInfo = {}
    awsWindowsInfo = {}
    user                =       request.user
    awsServers          =       Aws.objects.all()

    awsUbuntus          =       awsServers.filter(serverType='Ubuntu')
    awsWindows          =       awsServers.filter(serverType='Windows')

    disablestartRestartButton   =   "disabled"   
    startRestart                =   "Start"
    # Start for AWS Ubuntu Servers
    for awsUbuntu  in awsUbuntus:
        ubuntuSession = boto3.Session( 
                      aws_access_key_id=awsUbuntu.accessKeyID, 
                      aws_secret_access_key=awsUbuntu.secretAccessKey, 
                      region_name=awsUbuntu.region
                      )
        ubuntu_client  =  ubuntuSession.client('ec2') 
        
        ubuntuResponse      =   ubuntu_client.describe_instance_status(
            InstanceIds     =   [awsUbuntu.instanceID],
            IncludeAllInstances =   True
        )

       
        ubuntuInstanceStatus          = ubuntuResponse['InstanceStatuses'][0]['InstanceStatus']['Status']
        ubuntuSystemStatus            = ubuntuResponse['InstanceStatuses'][0]['SystemStatus']['Status']
        ubuntuInstanceStates          = ubuntuResponse['InstanceStatuses'][0]['InstanceState']['Name']

       

        if str(ubuntuInstanceStatus) == 'ok' and str(ubuntuSystemStatus) == 'ok' and str(ubuntuInstanceStates )=='running':
            # disableStopButton    =   ""
            # serverReady                 =   "Ready"
            startRestart                =   "Restart"
            disablestartRestartButton   =   ""
           

        elif str(ubuntuInstanceStatus) != 'ok' and str(ubuntuSystemStatus) != 'ok' and str(ubuntuInstanceStates )=='running':
            disablestartRestartButton   =   "disabled"   
                
            startRestart                 =   "Restart"

        
        elif str(ubuntuInstanceStatus) != 'ok' and str(ubuntuSystemStatus) != 'ok' and str(ubuntuInstanceStates )=='stopped':
            startRestart                 =   "Start"
            disablestartRestartButton    =   ""
            

        # for RDP Button enable/disable


            
        # else:
        #     # disableStopButton    =   "disabled"
        #     serverReady          =   "Not Ready"
        #     startReboot          =   "Start"       

        
        if str(ubuntuInstanceStates )=='running':
            disableStopButton    =   ""
        else:
            disableStopButton    =   "disabled"       

        awsUbuntuInfo[awsUbuntu.id] = { 
                                'database'                  : awsUbuntu.database,
                                'instanceName'              : awsUbuntu.instanceName,
                                'ubuntuInstanceStatus'      : ubuntuInstanceStatus, 
                                'ubuntuSystemStatus'        : ubuntuSystemStatus,
                                'disableStopButton'         : disableStopButton,
                                # 'serverReady'           : serverReady,
                                'disablestartRestartButton' : disablestartRestartButton,
                                'startRestart'              : startRestart,
                                'ubuntuInstanceStates'      : ubuntuInstanceStates,   
                                         
                                }
        ubuntuSession          =   None
        ubuntu_client          =   None
        ubuntuResponse         =   None

    # End for AWS Ubuntu Servers

    # Start for AWS Windows Servers

    for awsWindow  in awsWindows:
        windowsSession = boto3.Session( 
                      aws_access_key_id=awsWindow.accessKeyID, 
                      aws_secret_access_key=awsWindow.secretAccessKey, 
                      region_name=awsWindow.region
                      )
        windows_client  =  windowsSession.client('ec2') 
        
        windowResponse      =   windows_client.describe_instance_status(
            InstanceIds     =   [awsWindow.instanceID],
            IncludeAllInstances =   True
        )

       
        windowInstanceStatus          = windowResponse['InstanceStatuses'][0]['InstanceStatus']['Status']
        windowSystemStatus            = windowResponse['InstanceStatuses'][0]['SystemStatus']['Status']
        windowInstanceStates          = windowResponse['InstanceStatuses'][0]['InstanceState']['Name']

        disableRDPButton             =   "disabled"

        if str(windowInstanceStatus) == 'ok' and str(windowSystemStatus) == 'ok' and str(windowInstanceStates )=='running':
            # disableStopButton    =   ""
            # serverReady                 =   "Ready"
            startRestart                =   "Restart"
            disablestartRestartButton    =   ""
            disableRDPButton            =   ""  

        elif str(windowInstanceStatus) != 'ok' and str(windowSystemStatus) != 'ok' and str(windowInstanceStates )=='running':
            disablestartRestartButton    =   "disabled"            
            startRestart                 =   "Restart"
            disableRDPButton             =   "disabled"
        
        elif str(windowInstanceStatus) != 'ok' and str(windowSystemStatus) != 'ok' and str(windowInstanceStates )=='stopped':
            startRestart                 =   "Start"
            disablestartRestartButton    =   ""
            disableRDPButton             =   "disabled"

        
    
        # else:
        #     # disableStopButton    =   "disabled"
        #     serverReady          =   "Not Ready"
        #     startReboot          =   "Start"       

        
        if str(windowInstanceStates )=='running':
            
            disableStopButton    =   ""
        else:
            
            disableStopButton    =   "disabled"


        awsWindowsInfo[awsWindow.id] = { 
                                'database'                      : awsWindow.database,
                                'instanceName'                  : awsWindow.instanceName,
                                'rdpPass'                       : awsWindow.rdpPass,
                                'windowInstanceStatus'          : windowInstanceStatus, 
                                'windowSystemStatus'            : windowSystemStatus,
                                'disableStopButton'             : disableStopButton,
                                'disablestartRestartButton'     : disablestartRestartButton,
                                # 'serverReady'           : serverReady,
                                'startRestart'                  : startRestart,
                                'windowInstanceStates'          : windowInstanceStates,
                                'disableRDPButton'              : disableRDPButton   
                                  
                                }
        windowsSession      =   None
        windows_client      =   None
        windowResponse      =   None
    
    # End for AWS Windows Servers

    context     =   {
        # 'awsUbuntus' : awsUbuntus,
        # 'awsWindows': awsWindows,
        # 'awsURL': awsURL,
        'awsUbuntuInfo' :awsUbuntuInfo,
        'awsWindowsInfo': awsWindowsInfo
        }


    return render (request, 'aws/index.html', context)


@login_required(login_url= '/users/login')
def addaccount(request):
    user                    =         request.user
    awsaccounts             =         Awsaccounts.objects.all()

    return render (request, 'aws/addaccount.html', {'awsaccounts' : awsaccounts})


@login_required(login_url= '/users/login')
def processaddaccount(request):
    user                    = request.user

    getAccountName          = request.POST.get('accountName')
    awsaccount              = Awsaccounts.objects.get(accountName=getAccountName)
    accountName             = awsaccount.accountName
    accountID               = awsaccount.accountID
    accountUser             = awsaccount.accountUser
    accessKeyID             = awsaccount.accessKeyID
    secretAccessKey         = awsaccount.secretAccessKey
    region                  = awsaccount.region
    instanceName            = request.POST.get('instanceName')
    instanceID              = request.POST.get('instanceID')
    serverIP                = request.POST.get('serverIP')
    database                = request.POST.get('database')
    serverType              = request.POST.get('serverType')
    setupDate               = datetime.now().date()
    # return render ('')

    newAWSAccount = Aws.objects.create(accountName=accountName, 
        accountID=accountID,
        accountUser=accountUser,
        accessKeyID=accessKeyID,
        secretAccessKey=secretAccessKey,
        region=region,
        instanceName=instanceName,
        instanceID=instanceID,
        serverIP=serverIP,
        database=database,
        serverType=serverType,
        setupDate=setupDate)

    newAWSAccount.save()

    # return render (request, 'aws/awsservers.html', {})
    return HttpResponseRedirect('/aws', {})


@login_required(login_url= '/users/login')
def awsaccounts(request):

templates/aws/index.html
{% extends 'base.html' %}

{% block title %} Users List {% endblock %}

{% block content %} 


    <!-- <p>Current: {{currentcount}}, Exp: {{expcount}}, Total: {{total}}</p> -->
    <!-- <form action="{% url 'mmaptsp2:search' %}" method="GET">
        <div class="input-group">
            <input type="text" class="form-control" name="search" value= "{{term}}" placeholder="Search">
            <div class="input-group-append">
                <button type="submit" class="btn btn-success">Search</button>
            </div>
        </div>
    </form> -->

    <h3 class = "text-center mb-4 mt-4" >Ubuntu Servers</h3>

    {% if awsUbuntuInfo %}
        <div class="table-responsive rounded">
            <table class = "table table-dark table-bordered table-striped table-hover table-sm">
                <thead>
                    <tr>
                        <th class="align-middle text-center">#</th>
                        <!-- <th class="align-middle text-center">Server ID</th> -->
                        <th class="align-middle text-center">Server Name</th>                        
                        <th class="align-middle text-center">Databases</th>
                        <th class="align-middle text-center">Instance State</th>
                        <th class="align-middle text-center">Instance Status</th>     
                        <th class="align-middle text-center">System Status</th> 
                        <th class="align-middle text-center">Actions</th>
                        
                    </tr>     
                </thead>

                <tbody>
                    {% for key, values in awsUbuntuInfo.items %}
                    <tr height="20px">
                        <td class="align-middle text-center">{{ forloop.counter }}</td>                        
                        <!-- <td class="align-middle text-center">{{ awsUbuntu.id }}</td> -->
                        <td class="align-middle">{{ values.instanceName }}</td>                          
                        <td class="align-middle">{{ values.database }}</td>                        
                        <td class="align-middle text-center">{{ values.ubuntuInstanceStates }}</td>
                        <td class="align-middle text-center">{{ values.ubuntuInstanceStatus }}</td>
                        <td class="align-middle text-center">{{ values.ubuntuSystemStatus }}</td>
                        <td class="align-middle text-center">
                            <div class = "text-center mb-4">
                                <a href="{% url 'aws:startreserver' key %}"  class="btn btn-success mt-2 align-middle {{values.disablestartRestartButton}}"> {{values.startRestart}} </a>
                            <!-- <button type="cancel" class="btn btn-dark mt-2">Cancel</button> --->
                            {% if values.ubuntuInstanceStates == 'running'%}
                                <a href="{% url 'aws:stopserver' key %}"  class="btn btn-danger mt-2 align-middle {{ values.disableStopButton }}">Stop</a>
                            {% else %}
                                <a href="#"  class="btn btn-danger mt-2 align-middle {{ values.disableStopButton }}">Stop</a>
                            {% endif %}
                            </div>
                        </td>
                        <!-- <td>{{ mmap.mmap_branch }}</td> -->
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="table-responsive text-center" style="margin-top: -15px;">
            <thead class="text-center">
                <tr class="text-center">
                    <th class="align-middle text-center">
                        <a href="{% url 'aws:startareaservers' 'AllUbuntu' 'Start' %}"  class="btn btn-success mt-2 align-middle">Start All Ubuntu Servers</a>
                    </th>  
                    <th class="align-middle text-center">
                        <a href="{% url 'aws:startareaservers' 'AllUbuntu' 'Stop' %}"  class="btn btn-danger mt-2 align-middle">Stop All Ubuntu Servers</a>
                    </th>       
                </tr>     
            </thead>

        </div>

    {% endif %}
   


    <h3 class = "text-center mb-4 mt-4" >Windows Servers</h3>

    {% if awsWindowsInfo %}
        <div class="table-responsive rounded">
            <table class = "table table-dark table-bordered table-striped table-hover table-sm">
                <thead>
                    <tr>
                        <th class="align-middle text-center">#</th>
                        
                        <th class="align-middle text-center">Server Name</th>                        
                        <th class="align-middle text-center">Instance States</th>
                        <th class="align-middle text-center">Instance Status</th>
                        <th class="align-middle text-center">System Status</th>
                        <th class="align-middle text-center">RDP</th>                        
                        <th class="align-middle text-center">Actions</th>
                        
                    </tr>     
                </thead>

                <tbody>
                    {% for key, values in awsWindowsInfo.items %}
                    <tr>
                        <td class="align-middle text-center">{{ forloop.counter }}</td>                        
                        
                        <td class="align-middle">{{ values.instanceName }}</td>                          
                        <td class="align-middle text-center">{{ values.windowInstanceStates }}</td>                        
                        <td class="align-middle text-center">{{ values.windowInstanceStatus  }}</td>
                        <td class="align-middle text-center">{{ values.windowSystemStatus  }}</td>
                        <td class="align-middle text-center">
                            <div class = "text-center mb-4"> 
                            {% if values.disableRDPButton == "disabled" %}
                                <a href="#"  class="btn btn-success mt-2 align-middle {{values.disableRDPButton}} ">Remote Desktop</a>
                            {% else %}
                                <a href="{% url 'aws:instancerdp' key %}"  class="btn btn-success mt-2 align-middle {{values.disableRDPButton}} btn-rdp"  data-sid="{{values.rdpPass}}">Remote Desktop</a>
                            {% endif %}
                            </div> 
                        </td>
                        <td class="align-middle text-center">
                            <div class = "text-center mb-4">
                            {% if values.disablestartRestartButton == "disabled" %}
                                <a href="#"  class="btn btn-success mt-2 align-middle {{values.disablestartRestartButton}} "> {{values.startRestart}} </a>
                            {% else %}
                                <a href="{% url 'aws:startreserver' key %}"  class="btn btn-success mt-2 align-middle {{values.disablestartRestartButton}} "> {{values.startRestart}} </a>
                            {% endif %}
                            <!-- <button type="cancel" class="btn btn-dark mt-2">Cancel</button> --->
                            {% if values.windowInstanceStates == 'running'%}
                                <a href="{% url 'aws:stopserver' key %}"  class="btn btn-danger mt-2 align-middle {{ values.disableStopButton }}">Stop</a>
                            {% else %}
                                <a href="#"  class="btn btn-danger mt-2 align-middle {{ values.disableStopButton }}">Stop</a>
                            {% endif %}
                            </div>
                        </td>
                        <!-- <td>{{ mmap.mmap_branch }}</td> -->
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>    
        <div class="table-responsive text-center mb-2" style="margin-top: -15px;">
            <thead class="text-center">
                <tr class="text-center"> 
                    <th class="align-middle text-center">
                        <a href="{% url 'aws:startareaservers' 'AllWindows' 'Stop' %}"  class="btn btn-danger mt-2 align-middle">Stop All Windows Servers</a>
                    </th>       
                </tr>     
            </thead>

        </div>
    
    {% endif %}
    <script>
        $(document).ready(function(){
            $(".btn-rdp").on("click", function(){
                let rdpPass = $(this).attr('data-sid');
                var $rdp    = $("<input>");
                $("body").append($rdp);
                $rdp.val(rdpPass).select();
                document.execCommand("copy");
                $rdp.remove();
            });            

        });
    </script>
{% endblock %}

templates/aws/windowsservers.html
{% extends 'base.html' %}

{% block title %} Users List {% endblock %}

{% block content %} 
    <h3 class = "text-center" >Windows Servers</h3>

    {% if windowsServers %}
        <div class="table-responsive">
            <table class = "table table-dark table-bordered table-striped table-hover table-sm">
                <thead>
                    <tr>
                        <th class="align-middle text-center">#</th>
                        
                        <th class="align-middle text-center">Server Name</th>                        
                        <th class="align-middle text-center">Instance States</th>
                        <th class="align-middle text-center">Instance Status</th>
                        <th class="align-middle text-center">System Status</th>
                        <th class="align-middle text-center">RDP</th>   
                        <!-- <th class="align-middle text-center">RDP Pass</th>                           -->
                        <th class="align-middle text-center">Actions</th>
                        
                    </tr>     
                </thead>

                <tbody>
                    {% for key, values in windowsServers.items %}
                    <tr>
                        <td class="align-middle text-center">{{ forloop.counter }}</td>                        
                        
                        <td class="align-middle">{{ values.instanceName }}</td>                          
                        <td class="align-middle text-center">{{ values.windowsInstanceStates }}</td>                        
                        <td class="align-middle text-center">{{ values.windowsInstanceStatus  }}</td>
                        <td class="align-middle text-center">{{ values.windowsSystemStatus  }}</td>
                        <td class="align-middle text-center">
                            <div class = "text-center mb-4"> 
                            {% if values.disableRDPButton == "disabled" %}
                                <a href="#"  class="btn btn-success mt-2 align-middle {{values.disableRDPButton}} ">Remote Desktop</a>
                            {% else %}
                                <a href="{% url 'aws:instancerdp' key %}"  class="btn btn-success mt-2 align-middle {{values.disableRDPButton}} btn-rdp" data-sid="{{values.rdpPass}}">Remote Desktop</a>
                            {% endif %}
                            </div> 
                        </td>
                        
                        <td class="align-middle text-center">
                            <div class = "text-center mb-4">
                            {% if values.disablestartRestartButton == "disabled" %}
                                <a href="#"  class="btn btn-success mt-2 align-middle {{values.disablestartRestartButton}} "> {{values.startRestart}} </a>
                            {% else %}
                                <a href="{% url 'aws:startrewindowsservers' key %}"  class="btn btn-success mt-2 align-middle {{values.disablestartRestartButton}} "> {{values.startRestart}} </a>
                            {% endif %}
                            
                            {% if values.windowsInstanceStates == 'running'%}
                                <a href="{% url 'aws:stopwindowsservers' key %}"  class="btn btn-danger mt-2 align-middle {{ values.disableStopButton }}">Stop</a>
                            {% else %}
                                <a href="#"  class="btn btn-danger mt-2 align-middle {{ values.disableStopButton }}">Stop</a>
                            {% endif %}
                            </div>
                        </td>
                       
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
        <div class="table-responsive text-center mb-2" style = "margin-top: -10px;">
            <thead class="text-center">
                <tr class="text-center">
                    <th class="align-middle text-center">
                        <a href="{% url 'aws:ssallwindowsservers' 1 %}"  class="btn btn-success  align-middle" >Start All Windows Servers</a>
                    </th>  
                    <th class="align-middle text-center">
                        <a href="{% url 'aws:ssallwindowsservers' 0 %}"  class="btn btn-danger align-middle">Stop All Windows Servers</a>
                    </th>       
                </tr>     
            </thead>
    
        </div>
    
    {% else %}
    <p>No records available</p>

    {% endif %}

    <script>
        $(document).ready(function(){
            $(".btn-rdp").on("click", function(){
                let rdpPass = $(this).attr('data-sid');
                var $rdp    = $("<input>");
                $("body").append($rdp);
                $rdp.val(rdpPass).select();
                document.execCommand("copy");
                $rdp.remove();
            });            

        });
    </script>
{% endblock %}