aws/urls.py
from django.contrib import admin
from django.urls import include, path, re_path as url
from django.views.static import serve
from django.conf import settings
from . import views

app_name = 'aws'

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path ('', views.index, name='index'),
    path ('addaccount/', views.addaccount, name='addaccount'),
    path ('processaddaccount/', views.processaddaccount, name='processaddaccount'),
    path ('awsaccounts/', views.awsaccounts, name='awsaccounts'),
    path ('<int:serverid>/startreserver/', views.startreserver, name='startreserver'),
    path ('<int:serverid>/stopserver/', views.stopserver, name='stopserver'),
    path ('<str:instanceid>/instancerdp/', views.instancerdp, name='instancerdp'),
    path ('ubuntuservers/', views.ubuntuservers, name='ubuntuservers'),
    path ('<int:serverid>/startreubuntuservers/', views.startreubuntuservers, name='startreubuntuservers'),
    path ('<int:serverid>/stopubuntuservers/', views.stopubuntuservers, name='stopubuntuservers'),
    path ('windowsservers/', views.windowsservers, name='windowsservers'),
    path ('<int:serverid>/startrewindowsservers/', views.startrewindowsservers, name='startrewindowsservers'),
    path ('<int:serverid>/stopwindowsservers/', views.stopwindowsservers, name='stopwindowsservers'),    
    #ubuntuservers page

    path ('<str:area>/<str:action>/startareaservers/', views.startareaservers, name='startareaservers'),
    path ('<int:stopstart>/ssallwindowsservers/', views.ssallwindowsservers, name='ssallwindowsservers'),
    # path ('<int:serverid>/winrdpaccess/', views.winrdpaccess, name='winrdpaccess'),
]

clients/urls.py
from django.urls import path, re_path as url
from django.views.static import serve
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'clients'
urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('', views.index, name='index'),
    path('search',views.search, name='search'),
    path('addclient',views.addclient, name='addclient'),
    path('cancelledclient',views.cancelledclient, name='cancelledclient'),
    path('processaddclient',views.processaddclient, name='processaddclient'),
    path('<int:profile_id>/clientdetail/',views.clientdetail, name='clientdetail'),
    path('<int:profile_id>/cancelledclientdetail/',views.cancelledclientdetail, name='cancelledclientdetail'),
    # path('<int:profile_id>/clientdelete/',views.clientdelete, name='clientdelete'),
    path('<int:profile_id>/clientdisable/',views.clientdisable, name='clientdisable'),
    path('<int:profile_id>/clientedit/',views.clientedit, name='clientedit'),
    path('<int:profile_id>/processclientedit/',views.processclientedit, name='processclientedit'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kmsystem/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path ('', views.index, name='index'),
    path ('event/', include ('event.urls')),
    path ('aws/', include ('aws.urls')),
    path ('mmaptsp2/', include ('mmaptsp2.urls')),
    path ('clients/', include ('clients.urls')),
    path ('users/', include ('users.urls')),
    path('admin/', admin.site.urls),   
    
]

mmaptsp2/urls.py
from django.urls import path, re_path as url
from django.views.static import serve
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'mmaptsp2'
urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('', views.index, name='index'),    
    path('cancelledmmap', views.cancelledmmap, name='cancelledmmap'),   
    path('loadclient', views.loadclient, name='loadclient'),
    path('search', views.search, name='search'),
    path('searchclient',views.searchclient, name='searchclient'),
    path('<int:profile_id>/addmmap', views.addmmap, name='addmmap'),
    path('<int:profile_id>/mmapdetail/',views.mmapdetail, name='mmapdetail'),
    path('<int:mmap_id>/mmapedit/',views.mmapedit, name='mmapedit'),
    # path('<int:mmap_id>/mmapdelete/',views.mmapdelete, name='mmapdelete'),
    path('<int:mmap_id>/mmapcancel/',views.mmapcancel, name='mmapcancel'),
    path('<int:mmap_id>/processmmapedit/',views.processmmapedit, name='processmmapedit'),
    path('processaddmmap', views.processaddmmap, name='processaddmmap'),
    path('patchbenmmapid', views.patchbenmmapid, name='patchbenmmapid'),
    path('patchsccn', views.patchsccn, name='patchsccn'),
    path('filterby', views.filterby, name='filterby'),
    path('processfilterby', views.processfilterby, name='processfilterby'),
    path('allexpcurrent/<str:exporcurrent>/', views.allexpcurrent, name='allexpcurrent'),
    path('<int:profile_id>/mmapexpdetail/',views.mmapexpdetail, name='mmapexpdetail'),
    path('allexpcurrentexportdata/<str:exporttype>/', views.allexpcurrentexportdata, name='allexpcurrentexportdata'),
    path('exportdata/<str:exporttype>',views.exportdata, name='exportdata'),
    path('csv-upload/',views.csv_upload, name='csv_upload'),
    path('mmapclaim/',views.mmapclaim, name='mmapclaim'),
    path('newrenewstatus/',views.newrenewstatus, name='newrenewstatus'),
    path('<int:profile_id>/mmapdetailpdf/',views.mmapdetailpdf, name='mmapdetailpdf'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import re_path as url
# from django.conf import settings
from django.views.static import serve

from django.urls import path
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'users'
urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    path('', views.index, name='index'),
    path('login',views.loginview, name='loginview'),
    path('login/process',views.process, name='process'),
    path('logout',views.processlogout, name='processlogout'),
    path('add',views.add, name='add'),
    # path('userreg',views.userreg, name='userreg'),
    path('search',views.search, name='search'),
    path('processadd',views.processadd, name='processadd'),
    path('<int:profile_id>/detail/',views.detail, name='detail'),
    path('<int:profile_id>/delete/',views.delete, name='delete'),
    path('<int:profile_id>/edit/',views.edit, name='edit'),
    path('<int:profile_id>/processedit/',views.processedit, name='processedit'),
    path('addcomment',views.addcomment, name='addcomment'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/forms.py
# from django.forms import ModelForm
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User
# from django import forms


# class CreateUserForm(UserCreationForm):
#     class meta:
#         model   =   User
#         fields =    ['user_name', 'user_email', 'user_fname', 'user_lname','password1', 'password2']

users/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .models import User, Comment
from django.core.paginator import Paginator
from django.db.models import Q
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate, logout, login
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required, permission_required
from clients.models import Branch, Client
from mmaptsp2.models import Mmap, Beneficiary
from datetime import datetime, timedelta

# from .forms import CreateUserForm

# def userreg(request):
#     form        =       CreateUserForm()
#     if request.method   ==   'POST':
#         form    =       CreateUserForm(request.POST)
#         if form.is_valid():
#             form.save()

#     context     =       {'form': form}
#     return render(request, 'users/userreg.html', context)


@login_required(login_url= '/users/login')
def index(request):
    #user_list = User.objects.order_by('-id')[:5]
    #context = {'user_list': user_list}
    #return render(request, 'users/index.html', context)
    datetoday = datetime.now().date()
    #expiration validation
    expiration_validation   =   Mmap.objects.filter(expired_status="False")
    # exp_count               =   expiration_validation.count()
    user = request.user
       


    for clientexp   in expiration_validation:
        if clientexp.mmap_expired < datetoday:
            update_expired  =   get_object_or_404(Mmap, pk=clientexp.id)
            update_expired.expired_status  =   "True"
            update_expired.save()
        

    
    user_list       =       User.objects.all().order_by('-id')

    if user.can_selectbranch==False:
        user_list = User.objects.filter(user_branch=user.user_branch)


    paginator       =       Paginator(user_list, 5)    
    page_number     =       request.GET.get('page')
    user_list       =       paginator.get_page(page_number)

    datenow         =       datetime.now().date()
    fdatenow        =       datenow.strftime("%Y-%m-%d") 
    days30          =       datenow + timedelta(days=30)
    fdays30         =       days30.strftime("%Y-%m-%d") 
    mmapraw         =       Mmap.objects.filter(mmap_expired__range=[fdatenow, fdays30]).order_by('mmap_expired')
    mmap            =       mmapraw.filter(expired_status="False")
    # mmapfilter = mmap.filter(mmap_branch='Lutopan')
    
    if user.can_selectbranch==False:
        mmap = mmap.filter(mmap_branch=user.user_branch)

    context = {'page_obj': user_list, 'mmap': mmap, 'datenow': fdatenow, 'days30' : fdays30}    

    return render (request, 'users/index.html', context)

@login_required(login_url= '/users/login')
def search(request):
    term = request.GET.get('search', '')
    user_list = User.objects.filter(Q(user_fname__icontains=term) | Q(user_lname__icontains=term)).order_by('-id')
    paginator = Paginator(user_list, 5)    
    page_number = request.GET.get('page')
    user_list = paginator.get_page(page_number)
    return render (request, 'users/index.html', {'page_obj': user_list})

@login_required(login_url= '/users/login')
def add(request):
    branches = Branch.objects.only('branches')
    context = {'branches': branches}
    return render(request, 'users/add.html', context)

@login_required(login_url= '/users/login')
def processadd(request):
    user_name = request.POST.get('user_name')
    fname = request.POST.get('fname')
    lname = request.POST.get('lname')
    email = request.POST.get('email')
    user_branch = request.POST.get('user_branch')
    position = request.POST.get('position')
    
    if request.FILES.get('image'):
        user_pic = request.FILES.get('image')
    else:
        user_pic='profile_pic/default_image.jpg'

    try:

        m=User.objects.get(user_name=user_name)
        #if username already exist
        return render(request, 'users/add.html', { 
            'error_message': "Username already exist: " + user_name, 'fname': fname, 'lname': lname, 'email':email, 'position': position,
                        'user_name': user_name, 'user_branch': user_branch
            })

        n=User.objects.get(user_email=email)
        #if email already exist
        return render(request, 'users/add.html', { 
            'error_message': "Duplicated Email: " + email, 'fname': fname, 'lname': lname, 'email':email, 'position': position,
                        'user_name': user_name, 'user_branch': user_branch
            })

    except ObjectDoesNotExist:
        user=User.objects.create(user_email=email, user_name=user_name, user_fname=fname,
        user_lname=lname, user_branch=user_branch, user_position=position, user_image=user_pic)
        user.save()
        return HttpResponseRedirect('/users')

@login_required(login_url= '/users/login')        
def detail(request, profile_id):
    try:
        user = User.objects.get(pk=profile_id)
        comments = Comment.objects.filter(user_id=profile_id)
        comments_count = Comment.objects.filter(user_id=profile_id).count()
        context = {'users': user, 
                    'comments': comments, 'comments_count': comments_count}
    except User.DoesNotExist:
        raise Http404("Profile does not exist")
    return render(request, 'users/detail.html', context)

@login_required(login_url= '/users/login')
def addcomment(request):
    comment_text = request.POST.get('comment')
    user_id = request.POST.get('user_id')
    name = request.POST.get('name')
    email = request.POST.get('email')

    comment = Comment.objects.create(user_id=user_id, body=comment_text, name=name, email=email)
    comment.save()
    return HttpResponseRedirect(reverse('users:detail', args=(user_id,)))
@login_required(login_url= '/users/login')
def delete(request, profile_id):
    User.objects.filter(id=profile_id).delete()
    return HttpResponseRedirect('/users')

@login_required(login_url= '/users/login')
@permission_required('users.change_user', login_url= '/users/login')
def edit(request, profile_id):
    try:
        user = User.objects.get(pk=profile_id)
        branches = Branch.objects.only('branches') 
    except User.DoesNotExist:
        raise Http404("Profile does not exist")
    return render(request, 'users/edit.html', {'users': user, 'branches': branches})

@login_required(login_url= '/users/login')
def processedit(request, profile_id):
    user=get_object_or_404(User, pk=profile_id)
    profile_pic=request.FILES.get('image')
    try:
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        email = request.POST.get('email')
        position = request.POST.get('position')
        user_branch = request.POST.get('user_branch')
    except(KeyError, User.DoesNotExist):
        return render(request, 'users/detail.html', {
            'user': user,
            'error_message': "Problem updating record",
        })
    else:
        user_profile = User.objects.get(id=profile_id)
        user_profile.user_fname=fname
        user_profile.user_lname=lname
        user_profile.user_email=email
        user_profile.user_branch=user_branch
        user_profile.user_position=position
        if profile_pic:
            user_profile.user_image=profile_pic
        user_profile.save()
        return HttpResponseRedirect(reverse('users:detail', args=(profile_id,)))

def loginview(request):
    return render(request, 'users/login.html')


def process(request):
    username=request.POST.get('username')
    password=request.POST.get('password')
    user = authenticate(username=username, password=password )
    if user is not None:
        login(request, user)
        
        return HttpResponseRedirect('/users')
        # return redirect('users:daysindex')
        # datenow = datetime.now()
        # days30 = datenow + timedelta(days=30)
        # mmap = Mmap.objects.filter(mmap_expired__range=[datenow, days30]).order_by('-mmap_expired')
        # users= User.objects.all().order_by('-id')

        # return render (request, '/users/index.html', {'mmap': mmap, 'datenow': datenow, 'days30':days30, 'page_obj': users })
    
    else:
        return render(request, 'users/login.html', {
            'error_message': "Login Failed"
        })

def processlogout(request):
    logout(request)
    return HttpResponseRedirect('/users/login')

# def daysindex(request, profile_id):
#     datenow = datetime.now()
#     days30 = datenow + timedelta(days=30)
#     mmap = Mmap.objects.filter(mmap_expired__range=[datenow, days30]).order_by('-mmap_expired')

#     return render (request, 'users/index2.html', {'mmap': mmap})

templates/users/add.html
{% extends 'base.html' %}

{% block title %} Add New User {% endblock %}

{% block content %} 

{% if error_message %}
    <p class = "alert alert-danger">
        <strong>{{ error_message }}</strong>
    </p>

{% endif %}
   <form action="{% url 'users:processadd' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group">
        <label>User Name</label>
        <input type="text" name="user_name" id="user_name" class="form-control" value="{{ user_name }}" required>
    </div>

    <div class="form-group">
        <label>First Name</label>
        <input type="text" name="fname" id="fname" class="form-control" value="{{ fname }}" required>
    </div>

    <div class="form-group">
        <label>Last Name</label>
        <input type="text" name="lname" id="lname" class="form-control" value="{{ lname }}"required>
    </div>

    <div class="form-group">
        <label>Email</label>
        <input type="email" name="email" id="email" class="form-control" value="{{ email }}" required>
    </div>

    <div class="form-group">
        <label>Branch</label>
        <select name = "user_branch" id = "user_branch"  class="custom-select custom-select-sm" value="{{ user.user_branch }}" required>
            <option selected>{{ user.user_branch }}</option>
        {% for branch in branches %}
            <option value="{{branch.branches}}">{{branch.branches}}</option>
        {% endfor %}
        <select>
    </div>

    <div class="form-group">
        <label>Position</label>
        <input type="text" name="position" id="position" class="form-control" value="{{ position }}"required>
    </div>

    <div class="form-group">
        <label>User Image</label>
        <input type="file" name="image" id="image">
    </div>

    <button type="submit" class = "btn btn-success mt-2">Add</button>

    


   </form>
{% endblock %}

templates/users/addbackup.html
{% extends 'base.html' %}

{% block title %} Add New User {% endblock %}

{% block content %} 

{% if error_message %}
    <p class = "alert alert-danger">
        <strong>{{ error_message }}</strong>
    </p>

{% endif %}
   <form action="{% url 'users:processadd' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-group">
        <label>First Name</label>
        <input type="text" name="fname" id="fname" class="form-control" value="{{ fname }}" required>
    </div>

    <div class="form-group">
        <label>Last Name</label>
        <input type="text" name="lname" id="lname" class="form-control" value="{{ lname }}"required>
    </div>

    <div class="form-group">
        <label>Email</label>
        <input type="email" name="email" id="email" class="form-control" value="{{ email }}" required>
    </div>

    <div class="form-group">
        <label>Position</label>
        <input type="text" name="position" id="position" class="form-control" value="{{ position }}"required>
    </div>

    <div class="form-group">
        <label>User Image</label>
        <input type="file" name="image" id="image">
    </div>

    <button type="submit" class = "btn btn-success mt-2">Add</button>

    


   </form>
{% endblock %}

templates/users/detail.html
{% extends 'base.html' %}

{% block title %} {{ users.user_fname }} {{ users.user_lname }} {% endblock %}

{% block content %}

{% if error_message %}
    <p class = "alert alert-danger"><strong>{{ error_message }}</strong></p>
{% endif %}
<div class="row">

    <div class="col-lg-4 text-center">
        <div class="mb-3"> 
            <h1>{{ users.user_fname }} {{ users.user_lname }}</h1>
            <p class="text-muted">{{ users.user_email }}</p>
            <p>Position: {{ users.user_position }}</p>
        </div>
        
        <div class="img-responsive align-center mb-2">
            <img src="/users/media/{{users.user_image}}" alt="user_profile" class="img-rounded" width="300">
        </div>

        <div class="btn-group d-flex mb-2" role="group">        
            {% if user.is_staff %}
                <a href="{% url 'users:delete' user.id %}" class="btn btn-sm btn-danger">Delete</a>
                <a href="{% url 'users:edit' users.id %}" class="btn btn-sm btn-info">Edit</a>
            {% endif %}
                <a href="{% url 'users:index' %}" class="btn btn-sm btn-success">Return</a>        
        </div>

    </div>

    <div class="col-lg-8">
        <h2>Comments</h2>
        <p class="text-muted">Total of {{ comments_count }}</p>
        {% if comments_count > 0 %}
            {% for comment in comments %}
                {% if comment.active %}
                    <p><strong>{{comment.name}}</strong>: {{comment.body}}</p>
                {% endif %}
            {% endfor %}
        {% endif %}
        <hr>
        <br>
        <form action="{% url 'users:addcomment' %} " method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>Comment</label>
                <textarea name="comment" id="comment" cols="30" rows="5"  class="form-control" required ></textarea>
            </div>
            <input type="hidden" name="user_id" id="user_id" value="{{ users.id }}" >
            <input type="hidden" name="name" id="name" value="{{ user.username }}" >
            <input type="hidden" name="email" id="email" value="{{ user.email }}" >

            <button type="submit" class="btn btn-sm btn-primary">Add Comment</button>
        </form>
    </div>
</div>




{% endblock %}

templates/users/index.html
{% extends 'base.html' %}

{% block title %} Users List {% endblock %}

{% block content %} 
   
    <p class="text-muted">Expires from {{ datenow }} to {{ days30 }}</p>
  

    <form action="{% url 'users:search' %}" method="GET">
        {% csrf_token %}
        <div class="input-group">
            <input type="text" class="form-control" name="search" placeholder="Search" required>
            <div class="input-group-append">
                <button type="submit" class="btn btn-success">Search</button>
            </div>
        </div>
    </form>

    <h1 class = "text-center mb-4 mt-4" >Users List</h1>

    {% if page_obj %}
        <div class="table-responsive">
            <table class = "table table-bordered table-striped table-hover">
                <thead>
                    <tr>                        
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>Profile Image</th>
                    </tr>     
                </thead>

                <tbody>
                    {% for user in page_obj %}
                        
                    <tr>                        
                        <td><a href="{% url 'users:detail' user.id %}">{{ user.user_fname }}</a></td>
                        <td><a href="{% url 'users:detail' user.id %}">{{ user.user_lname }}</a></td>
                        <td>{{ user.user_email }}</td>
                        <td class = "text-center">
                            <a href="{% url 'users:detail' user.id %}">
                                <img src = "media/{{ user.user_image }}" alt="userimage" width="35" class="rounded-circle"></td>
                            </a>
                        
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <ul class="pagination">

                {% if page_obj.has_previous %}
                    <li class="page-item"><a href="?page=1" class="page-link" >&laquo; First</a></li>
                    <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a></li>
                {% endif %}

                {% if page_obj.has_next %}
                    <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a></li>
                    <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">&raquo;Last</a></li>
                {% endif %}


            </ul>

        </div>
    
    {% else %}
    <p>No records available</p>

    {% endif %}

    
    {% if mmap %}
        <div class="table-responsive">
            <table class = "table table-bordered table-striped table-hover table-sm">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Branch</th>
                        <th>Registered Date</th>
                        <th>Expiration Date</th>
                        <th>Client ID</th>
                        <th>Application ID</th>
                        <th>Profile Image</th>
                    </tr>     
                </thead>

                <tbody>
                    {% for client in mmap %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'mmaptsp2:mmapdetail' client.id %}">
                            {{ client.mmap_name }}
                        </a></td>
                        <td>{{ client.mmap_branch }}</td>
                        <td>{{ client.mmap_setupdate }}</td>
                        <td>{{ client.mmap_expired }}</td>                        
                        <td class = "text-center"><a href="{% url 'clients:clientdetail' client.clientid %}">
                            {{ client.clientid }}
                        </a></td>
                        <td class = "text-center"><a href="{% url 'mmaptsp2:mmapdetail' client.id %}">
                            {{ client.id }}
                        </a></td>
                        <td class = "text-center">
                            
                                <img src = "media/{{ client.clientimg }}" alt="clientimage" height="35" class="rounded-circle">
                            
                        </td>   
                                     
                    </tr>
                    {% endfor %}
                </tbody>
            </table>


        </div>
        {{cliid}}
    {% else %}
    <p>No records available</p>
    
    {% endif %}
    
{% endblock %}

templates/users/index2.html
{% extends 'base.html' %}

{% block title %} Users List {% endblock %}

{% block content %} 
    {{ user }}

    {{ datenow }} <br/>
    {{ days30 }} <br/>
    <form action="{% url 'users:search' %}" method="GET">
        {% csrf_token %}
        <div class="input-group">
            <input type="text" class="form-control" name="search" placeholder="Search" required>
            <div class="input-group-append">
                <button type="submit" class="btn btn-success">Search</button>
            </div>
        </div>
    </form>

    <h1 class = "text-center mb-4 mt-4" >Users List</h1>

    {% if page_obj %}
        <div class="table-responsive">
            <table class = "table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Email Name</th>
                        <th>Profile Image</th>
                    </tr>     
                </thead>

                <tbody>
                    {% for user in page_obj %}
                    <tr>
                        <td>{{ user.user_fname }}</td>
                        <td>{{ user.user_lname }}</td>
                        <td>{{ user.user_email }}</td>
                        <td class = "text-center">
                            <a href="{% url 'users:detail' user.id %}">
                                <img src = "media/{{ user.user_image }}" alt="userimage" width="35" class="rounded-circle"></td>
                            </a>
                        
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <ul class="pagination">

                {% if page_obj.has_previous %}
                    <li class="page-item"><a href="?page=1" class="page-link" >&laquo; First</a></li>
                    <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a></li>
                {% endif %}

                {% if page_obj.has_next %}
                    <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a></li>
                    <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">&raquo;Last</a></li>
                {% endif %}


            </ul>

        </div>
    
    {% else %}
    <p>No records available</p>

    {% endif %}

    
    {% if mmap %}
        <div class="table-responsive">
            <table class = "table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th>First Name</th>
                        <th>Middle Name</th>
                        <th>Last Name</th>
                        <th>Email</th>
                        <th>ID</th>
                        <th>Profile Image</th>
                    </tr>     
                </thead>

                <tbody>
                    {% for client in mmap %}
                    <tr>
                        <td>{{ client.client_fname }}</td>
                        <td>{{ client.client_mname }}</td>
                        <td>{{ client.client_lname }}</td>
                        <td>{{ client.client_email }}</td>
                        <td>{{ client.id }}</td>
                        <td class = "text-center">
                            <a href="{% url 'mmaptsp2:addmmap' client.id %}">
                                <img src = "media/{{ client.client_image }}" alt="clientimage" width="35" class="rounded-circle"></td>
                            </a>            
                    </tr>
                    {% endfor %}
                </tbody>
            </table>


        </div>
    
    {% else %}
    <p>No records available</p>
    
    {% endif %}
    
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %} 
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-6 m-auto">
                {% if error_message %}
                    <p class="alert alert-danger">
                       <strong>{{ error_message }}</strong>
                    </p>
                {% endif %}

                <div class="text-center">
                    <h2>Login Form</h2>
                </div>
                
                <form action="{% url 'users:process' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Username</label>
                        <input type="text" name="username" id="username" class="form-control" placeholder="Enter username" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" name="password" id="password" class="form-control" placeholder="Enter password">
                    </div>
                    <button type="submit" class="btn btn-success">Login</button>
                </form>
            </div>
            
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
{% endblock %}